url: https://rakshazi.me
verification:
  yandex: 674fa753e7bdf300
  google: Y8tF7rwYIgFdDUFv_hWp6kt3gRRKEeCDMUeqaW2VVA0
meta:
  "index.html":
    canonical: /
    description: Backend Developer, DevOps
    image: profile/logo.png
    style: profile.css
    title: Nikita Chernyi
    twitter: rakshazi
    type: website

compress_html:
  clippings: all
  comments: all
  startings: all
  endings: all
  blanklines: false
  profile: false
